version: "2"
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile
      args:
          # packages versioning:

          PYTHON: '3.9'

          PIPOPTION: '--trusted-host pypi.tuna.tsinghua.edu.cn -i https://pypi.tuna.tsinghua.edu.cn/simple'

          IPYTHON: '7.28.*'
          PANDAS: '1.3.*'
          NUMPY: '1.21.*'
          NUMBA: '0.53.*'
          JUPYTERLAB: '3.1.*'

          PLOTLY: '5.*'
          IPYWIDGETS: '7.6.*'



    image: juypter_workspace_notebook
    ports:
      - "8888:8888"
    env_file: nb_secrets.env
    volumes:
      - report:/root/report
    restart: always

volumes:
  report:
