version: "2"
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile
      args:
          # packages versioning:
          MINICONDA_VERSION: '4.7.10'

          PYTHON: '3.7'

          NODEJS: '12.*'

          IPYTHON: '7.15.*'
          PYODBC: '4.0.*'
          PSYCOPG2: '2.8.*'
          XGBOOST: '1.1.*'
          PANDAS: '1.0.*'
          NUMPY: '1.19.*'
          NUMBA: '0.50.*'
          SCIKIT_LEARN: '0.19.*'
          JUPYTERLAB: '2.1.4'
          NOTEBOOK: '6.0.*'
          XEUS_PYTHON: '0.6.*'

          R_ESSENTIAL: '3.6.*'

          PYECHARTS: '1.*'
          PLOTLY: '4.*'
          IPYWIDGETS: '7.5.*'
          SEABORN: '0.10.*'

          LAB_MANAGER: '2.0'



    image: juypter_workspace_notebook
    ports:
      - "8888:8888"
    env_file: nb_secrets.env
    volumes:
      - report:/root/report
    restart: always

volumes:
  report:
