FROM juypter_workspace_notebook

MAINTAINER Simon MA <ma.yijun@outlook.com>

USER root

ARG JUPY_KERNEL_GATEWAY

RUN conda install -y jupyter_kernel_gateway=$JUPY_KERNEL_GATEWAY \
    && conda clean -y -a

CMD ["jupyter", "kernelgateway", "--KernelGatewayApp.ip=0.0.0.0"]